### ISSUE TITLE
Should Proprietary Relicensing poison pill omit child-of-automatic-relicensing from set of evaporated terms?

### ISSUE THREAD

**Issue by richardfontana** [copyleft-next/copyleft-next#27]
This is an issue that has arisen based on one of the suggested changes of @pchestek at 
https://github.com/richardfontana/copyleft-next/pull/19

@pchestek notes that in her fork she carved out the former section 6 ('Pass-Through' aka child-of-automatic-licensing) because it is not really a condition.

Assuming for sake of argument that it is not really a condition, the question here is whether it is nonetheless necessary or desirable to mention it as one of the terms that 'no longer apply to You' when 'We' do proprietary relicensing.

**Comment by pchestek** [comment]
As mentioned in #28, I don't see how this provision affects what the licensee may or may not do. (Perhaps are you thinking of "pass-through" as being an act taken on the part of the licensee-distributor, like a sublicense? But that's not the way you've worded paragraph 6). So the poison pill is irrelevant to paragraph 6 because it releases "You" from burdens, but "You" isn't burdened by anything in paragraph 6 (as I read it).

The poison pill is agnostic as to the licensee, that is, it is based on a time certain ("first Distribution"), not a time relative to any licensee. The "recipient" in paragraph 6 also becomes a "You" because they are now a direct licensee of the Received Work. So as written, the recipient would be relieved of the burdens in 4-9 if the triggering event happened, even if receiving the Received Work after the triggering event happened. Which I think is the right outcome; I think you want all recipients of the Received Work on equal footing.

**Comment by richardfontana** [comment]
Okay. I think what really concerns me is something orthogonal to this issue, which is just the desire to make section 4 more easily understandable (without making it longer of course).

**Comment by richardfontana** [comment]
Change applied in 11ef56b06b05cd4e30b39b6e5d4120b1404586e2. Closing.
