### ISSUE TITLE
Is YELLING (sections 15 and 16) necessary?

### ISSUE THREAD

**Issue by fmarier** [copyleft-next/copyleft-next#9]
These sections would be much more readable if they weren't all uppercase.

The fact that almost all free software licenses do it suggests that there is some legal requirement to highlight these sections differently. It is however interesting to look at version 2 of the MPL which uses a [different background color](https://www.mozilla.org/MPL/2.0/#disclaimer-of-warranty) or [an ascii border](https://www.mozilla.org/MPL/2.0/index.txt).

**Comment by richardfontana** [comment]
Early drafts of GPLv3 made the disclaimers lowercase because of the
same desire not to have 'yelling'. Certain US lawyers involved in the
drafting process then cited US legal authority suggesting the need for
such disclaimers to be "conspicuous". As the FSF noted in the GPLv3
Discussion Draft 3 Rationale (March 2007):

  There is authority under United States law suggesting that effective
  warranty disclaimers must be “conspicuous,” and that conspicuousness
  can be established by capitalization and is absent when a disclaimer
  has the same typeface as the terms surrounding it (see Stevenson
  v. TRW, Inc., 987 F.2d 288, 296 (5th Cir. 1993)). We have reason to
  doubt that such authority would apply to copyright licenses like the
  GPL. Nevertheless, pending further research, we have cautiously
  decided to restore the capitalization of both the warranty
  disclaimer and the liability limitation in Draft 3.

That "further research" was never done, to my recollection, though I
presume Mozilla researched the issue for MPL 2.0. 

I say for development purposes we should return to lowercase to make
it easier to read and discuss the provisions.

**Comment by webmink** [comment]
Would alternative approaches to making it conspicuous, such as adding a punctuation border above and below the section saying "=======  PLEASE ESPECIALLY NOTE THE FOLLOWING ======" or similar, meet the requirements of the statute?

**Comment by richardfontana** [comment]
Without actually resolving the substantive issue here, I've placed the disclaimer provisions in lowercase. https://github.com/richardfontana/GPL.next/commit/b2a816c026b9b5362c96f904e32c21a450858331

**Comment by tieguy** [comment]
Most statutes that specify typography for emphasis appear to require that emphasized text be "conspicuous," without defining "conspicuous." This has been traditionally been interpreted as ALL CAPS but need not be. See, e.g., discussion in "A Manual of Style for Contract Drafting," Ken Adams, at 15.32-15.41; "Typography for Lawyers," Matthew Butterick, at 86-89. UCC, which states that a warranty must be conspicuous (and may have inspired the commenters on GPL v3?), says that one way that a term can be conspicuous if it's "set off from surrounding text of the same size by symbols or other marks that call attention to the language." 1-201(10). That's the approach we took in MPL.

I would distinguish Stevenson v. TRW because that text was on the back of the page, and that other text around it was emphasized more strongly (using bold), whereas here the only emphasized text in the entire document is this particular passage. That said, I have not done a comprehensive review of the long list of cases cited by Stevenson. Richard, do you have a summer associate you could set on that problem? :)

**Comment by webmink** [comment]
I've made a placeholder proposal (and pull request) in [issue 10](https://github.com/richardfontana/GPL.next/issues/10).

**Comment by richardfontana** [comment]
I've adopted the MPL 2.0 approach, using asterisks to surround the disclaimer provisions.
